plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = "https://masa.dy.fi/maven/sakura-ryoko"
        content { includeGroupAndSubgroups("fi.dy.masa") }
    }
    maven { url = "https://maven.fallenbreath.me/releases"
        content { includeGroupAndSubgroups("me.fallenbreath") }
    }
    maven { url "https://maven.terraformersmc.com/releases/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    implementation "fi.dy.masa.malilib:malilib-fabric-26.2:0.29.3"
    implementation "fi.dy.masa.minihud:minihud-fabric-26.2:0.40.4"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release.set(25)
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}
