name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: mod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eun-search-${{ github.ref_name }}
          path: mod/build/libs/*.jar
